version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:12.15
    ports:
      - "5432:5432/tcp"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"